# Generated by Django 6.0.1 on 2026-05-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_landlordsettings_payout_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantinvite',
            name='otp_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tenantinvite',
            name='otp_locked',
            field=models.BooleanField(default=False),
        ),
    ]
