# Generated by Codex on 2026-06-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_subscription_phase2b"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptioninvoice",
            name="payment_reference",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=120,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="subscriptioninvoice",
            name="payment_initiated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
