# Generated by Django 6.0.1 on 2026-06-03 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_subscription_payment_attempt_marker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlordsettings',
            name='collection_mode',
            field=models.CharField(choices=[('custody_legacy', 'KRIB custody legacy'), ('direct_paybill', 'Direct landlord Paybill')], default='direct_paybill', max_length=30),
        ),
    ]
